" Install vim-plug if needed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Sudo Helper
Plug 'lambdalisue/suda.vim'

" Autocomplete + Snippets
"Plug 'roxma/nvim-completion-manager' | Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Editorconfig
Plug 'editorconfig/editorconfig-vim'

" Nerd Commenter
Plug 'scrooloose/nerdcommenter'

" Vim Shebang
Plug 'sbdchd/vim-shebang'

" Initialize plugin system
call plug#end()

" Enable Smart Sudo
let g:suda_smart_edit = 1

" Set Python Exec
let g:python3_host_prog = '/home/bradenmars/.pyenv/versions/3.7.3/bin/python'

" Enable Mouse
set mouse=a

" Status bar
set laststatus=2

" Line Numbers
set number

" Encoding
set encoding=utf-8

" Always use System Clipboard
set clipboard+=unnamedplus

" Highlight matching search patterns
set hlsearch
" Enable incremental search
set incsearch
" Include matching uppercase words with lowercase search term
set ignorecase
" Include only uppercase words with uppercase search term
set smartcase

" Automatically save and load folds
"autocmd BufWinLeave *.* mkview
"autocmd BufWinEnter *.* silent loadview"

" Set Leader
let mapleader = ","
