# .zshenv
#
# `.zshenv' is sourced on all invocations of the shell, unless the -f option is set.
# It should contain commands to set the command search path, plus other important environment variables.
# `.zshenv' should not contain commands that produce output or assume the shell is attached to a tty.
#
# see @ http://zsh.sourceforge.net/Intro/intro_3.html

# System
export PATH=/usr/local/bin:$HOME/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export SSH_KEY_PATH="~/.ssh/rsa_id"
export MANPATH="/usr/local/man:$MANPATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib:/usr/lib32"

# Preferred editor for local and remote sessions
export EDITOR='nvim'
export BROWSER='firefox-developer-edition'

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Qt5 Wayland
export QT_QPA_PLATFORM=wayland
#export QT_QPA_PLATFORM=xcb
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Clutter
export CLUTTER_BACKEND=wayland

# SDL2
export SDL_VIDEODRIVER=wayland

# ECORE
export ECORE_EVAS_EVAS_ENGINE=wayland

# ELM
export ELM_ENGINE=wayland

# Java
export _JAVA_AWT_WM_NONREPARENTING=1

# Locale(s)
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.utf8

# CFlags
export CFLAGS='-O2'

# GNUPG
export GPG_TTY=$(tty)

# Dotfiles
export DOTFILES="$HOME/dotfiles"
export DOTF_SCRIPTS="$HOME/.scripts"

# Local Binaries
export PATH="$HOME/.local/bin:$PATH"

# Go Env
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

# Add Yarn Global Bin Path
export PATH="$HOME/.yarn/bin:$PATH"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Poetry
export PATH="$HOME/.poetry/bin:$PATH"

# ElasticBeanstalk CLI
export PATH="/home/bradenmars/.ebcli-virtual-env/executables:$PATH"

# .vimrc
export MYVIMRC="~/.vimrc"

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
#source $HOME/.local/bin/virtualenvwrapper_lazy.sh

# XDG Config
export XDG_CONFIG_HOME=/home/bradenmars/.config
export XDG_CURRENT_DESKTOP=sway

# Scripts
export PATH="$PATH:/home/bradenmars/.scripts/bin"

# Android Env
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:~/.android/avd
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export ANDROID_NDK=$ANDROID_HOME/ndk-bundle

# LastPass
export LPASS_AGENT_TIMEOUT=0

# Qutebrowser
export QUTE_DOWNLOAD_DIR="$HOME/Downloads"

# Rofi -> Wofi
export ROFI_CMD="wofi"
export ROFI_ARGS="--conf $XDG_CONFIG_HOME/wofi/quteconfig -d"

# ASDF Version Management
export PATH="$HOME/.asdf/bin:$PATH"
