# .zshenv
#
# `.zshenv' is sourced on all invocations of the shell, unless the -f option is set.
# It should contain commands to set the command search path, plus other important environment variables.
# `.zshenv' should not contain commands that produce output or assume the shell is attached to a tty.
#
# see @ http://zsh.sourceforge.net/Intro/intro_3.html

# System
export PATH=/usr/local/bin:$HOME/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export SSH_KEY_PATH="~/.ssh/id_rsa"
export MANPATH="/usr/local/man:$MANPATH"
export LD_LIBRARY_PATH="/usr/lib:/usr/lib32:/usr/lib/jvm/$(archlinux-java get)/lib/server:${LD_LIBRARY_PATH}"

# make flags
export MAKEFLAGS="-j$(($(nproc)+1))"
[ -z "$_make_flags" ] || export MAKEFLAGS="${MAKEFLAGS} ${_make_flags}"

# Preferred editor for local and remote sessions
export EDITOR='nvim'
#export BROWSER='firefox'

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Qt5 Wayland
export QT_QPA_PLATFORM=wayland
#export QT_QPA_PLATFORM=xcb
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Clutter
export CLUTTER_BACKEND=wayland

# SDL2
export SDL_VIDEODRIVER=wayland

# ECORE
export ECORE_EVAS_EVAS_ENGINE=wayland

# ELM
export ELM_ENGINE=wayland

# Java
export _JAVA_AWT_WM_NONREPARENTING=1
#export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true ${_JAVA_OPTIONS}"

# Locale(s)
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.utf8

# Timezone
export TZ=America/Chicago

# CFlags
export CFLAGS='-O2'

# Rust
export RUSTFLAGS="-C opt-level=2"

# GNUPG
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

# Keychain (load only)
[ -z "$HOSTNAME" ] && HOSTNAME=$(uname -n)
[ -f $HOME/.keychain/$HOSTNAME-sh ] &&
	. $HOME/.keychain/$HOSTNAME-sh
[ -f $HOME/.keychain/$HOSTNAME-sh-gpg ] &&
	. $HOME/.keychain/$HOSTNAME-sh-gpg

# Dotfiles
export DOTFILES="$HOME/dotfiles"
export DOTF_SCRIPTS="$HOME/.scripts"

# Local Binaries
export PATH="$HOME/.local/bin:$PATH"

# Go Env
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

# Add Yarn Global Bin Path
export PATH="$HOME/.yarn/bin:$PATH"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Poetry
export PATH="$HOME/.poetry/bin:$PATH"

# ElasticBeanstalk CLI
export PATH="/home/bradenmars/.ebcli-virtual-env/executables:$PATH"

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
#source $HOME/.local/bin/virtualenvwrapper_lazy.sh

# XDG Config
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CURRENT_DESKTOP=sway

# Android Env
export ANDROID_HOME=/opt/android-sdk
export PATH=$PATH:~/.android/avd
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
# export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export ANDROID_NDK=$ANDROID_HOME/ndk-bundle

# LastPass
export LPASS_AGENT_TIMEOUT=0

# Qutebrowser
export QUTE_DOWNLOAD_DIR="$HOME/Downloads"

# Rofi -> Wofi
export ROFI_CMD="wofi"
export ROFI_ARGS="--conf $XDG_CONFIG_HOME/wofi/quteconfig -d"

# Informs mesa-git PKGBUILD to use the llvm from mesa-git repo.
#export MESA_WHICH_LLVM=3

# Jetbrains use JBR
#export IDEA_JDK=/usr/lib/jvm/jre-jetbrains
#export PHPSTORM_JDK=/usr/lib/jvm/jre-jetbrains
#export WEBIDE_JDK=/usr/lib/jvm/jre-jetbrains
#export PYCHARM_JDK=/usr/lib/jvm/jre-jetbrains
#export RUBYMINE_JDK=/usr/lib/jvm/jre-jetbrains
#export CL_JDK=/usr/lib/jvm/jre-jetbrains
export DATAGRIP_JDK=/usr/lib/jvm/jre-jetbrains
#export GOLAND_JDK=/usr/lib/jvm/jre-jetbrains
export WEBIDE_JDK=/usr/lib/jvm/jre-jetbrains
export PYCHARM_JDK=/usr/lib/jvm/jre-jetbrains
export STUDIO_JDK=/usr/lib/jvm/jre-jetbrains
unset MYVIMRC

# PNPM Global
export PNPM_HOME="/home/bradenmars/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

# GTK2
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

# Kubectl Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Scripts
export PATH="${PATH}:${HOME}/.scripts"

export STREAMLIT_TELEMETRY_ENABLED=false
