# .zshenv
#
# `.zshenv' is sourced on all invocations of the shell, unless the -f option is set. 
# It should contain commands to set the command search path, plus other important environment variables. 
# `.zshenv' should not contain commands that produce output or assume the shell is attached to a tty. 
#
# see @ http://zsh.sourceforge.net/Intro/intro_3.html

# System
export PATH=/usr/local/bin:$HOME/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="vim"
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Qt5 Wayland
export QT_QPA_PLATFORM=wayland

# Clutter
export CLUTTER_BACKEND=wayland

# SDL2
export SDL_VIDEODRIVER=wayland

# Kitty
export KITTY_DISABLE_WAYLAND=1
export KITTY_CONFIG_DIRECTORY="/home/bradenmars/.config/kitty"
export KITTY_THEME="Monokai Soda"

# Locale(s)
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
