# .zshrc
# ZSH Config
#
# See @ http://zsh.sourceforge.net/Intro/intro_3.html

# GNUPG Agent
gpg-connect-agent updatestartuptty /bye >/dev/null

# Keychain
keychain id_git --agents ssh --quiet


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Enable ZSH Profiling
#zmodload zsh/zprof

# Set Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Disable Update Prompt (Load time)
DISABLE_UPDATE_PROMPT=true

# Oh-My-Zsh Plugins
plugins=(
  httpie		     # httpie completions
  yarn			     # yarn completions
  asdf                       # extendable version manager
  #rbenv			     # rbenv completions
  fd 			     # find replacement
  rsync			     # rsync aliases
  #zsh-nvm		     # nvm lazy load and completions
  zsh-autosuggestions	     # auto suggestions
  autojump		     # 'j' command - smart cd
  gitfast		     # git... but fast
  git-extras		     # awesome git scripts
  evalcache		     # cache 'eval' commands
  alias-tips		     # informs you of an alias if one exists
  copyzshell		     # copy zsh config over ssh
  timewarrior                # timewarrior aliases / completion   
  systemd		     # systemd aliases
  autoupdate                 # auto update zsh plugins
  zsh-syntax-highlighting    # !! must be last - syntx hl
)

# ZSH Autosuggest
ZSH_AUTOSUGGEST_STRATEGY=(history)
ZSH_AUTOSUGGEST_USE_ASYNC=0 # was kind of buggy...

# Zsh Syntax Highlight
typeset -A ZSH_HIGHLIGHT_STYLES

# Zsh Record Mode (used for svgterm apps)
if [ -n "$ZSH_REC_MODE" ]; then
  echo "ZSH LOADED IN REC MODE"
  noload=(zsh-autosuggestions)
  for p in ${noload[@]}; do
    plugins=(${plugins[@]/$p/})
  done
  echo $plugins
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
  ZSH_HIGHLIGHT_STYLES[unknown - token]=none
  alias lstree="tree -a -L 2"
fi

# ZSH Syntax Highlight
ZSH_HIGHLIGHT_STYLES[path]=cyan

# ZSH-NVM Config
export NVM_DIR="$HOME/.nvm"
export NVM_LAZY_LOAD=true # Get rid of a 3s startup time
export NVM_NO_USE=true

# Load Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

## User configuration

# Load Scripts
source "$DOTF_SCRIPTS/load"

# Report ZSH Profiling
#zprof

## Powershell10k
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


