# .zshrc
# ZSH Config
#
# See @ http://zsh.sourceforge.net/Intro/intro_3.html

# GNUPG Agent
gpg-connect-agent updatestartuptty /bye > /dev/null


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
##: init direnv (see: https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-initialize-direnv-when-using-instant-prompt)
# . $HOME/.asdf/asdf.sh ## skip loading asdf to _not_ setup shims.
export ASDF_DIR="${HOME}/.asdf"
PATH="$PATH:${ASDF_DIR}/bin"
(( ${+commands[direnv]} )) && emulate zsh -c "$(asdf exec direnv export zsh)"
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
(( ${+commands[direnv]} )) && emulate zsh -c "$(asdf exec direnv hook zsh)"

# Enable ZSH Profiling
#zmodload zsh/zprof

# Set Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Disable Update Prompt (Load time)
DISABLE_UPDATE_PROMPT=true

# Auto Correct
# ENABLE_CORRECTION="true"

# Oh-My-Zsh Plugins
plugins=(
archlinux		             # httpie completions
httpie		               # httpie completions
adb 		                 # adb completions
dnote 		               # dnote completions
yarn			               # yarn completions
pnpm			               # pnpm completions
extract                  # determines and uses tar/7z/unzip/gzip etc
transfer                 # transfer cmd for transfer.sh
nmap                     # common nmap cmd aliases 
eksctl                   # eksctl completions
helm                     # helm completions
minikube                 # minikube completions
ansible                  # ansible completions/aliases
cmctl                    # cert-manager cli completions
fd 			                 # find replacement
aws 			               # aws completions
rsync			               # rsync aliases
python                   # python helpers
poetry                   # poetry completions
pip                      # pip completions 
command-not-found        # use pkgfile to find unknown commands
colored-man-pages	       # colorize man pages
common-aliases           # colorize man pages
copybuffer               # binds ctrl-o to copy currently typed cmd
docker                   # docker
docker-compose           # docker-compose aliases
dotnet                   # dotnet completion / aliases
git                      # git alias/completions 
gitfast		               # git... but fast
git-extras		           # awesome git scripts
git-escape-magic	       # escapes zsh stuff 
gh		                   # github cli
git-machete	             # git repo organize+rebase/merge workflow autom
evalcache		             # cache 'eval' commands
alias-finder		         # informs you of an alias if one exists
aliases		               # cheatsheet for aliases
tmux                     # tmux
ripgrep                  # rg completions
taskwarrior              # taskwarrior 
timewarrior              # timewarrior aliases / completion 
systemd		               # systemd aliases
urltools		             # provides cmds urlencode/urldecode
web-search		           # provides web_search/google cmd
fancy-ctrl-z		         # ctrl-z opens/closes vim
trash		                 # trash-cli completions
#flutter		               # flutter completions.
encode64                 # encode/decode64 cmds
kubectl                  # kubctl autocompletion
helm                     # helm autocompletion
autoupdate               # auto update zsh plugins
fzf                      # fzf plugin
#a5r                      # adstakr completions
per-directory-history    # directory history.
zoxide                   # better jump
zsh-interactive-cd       # interactive tab completion for cd
zsh-navigation-tools     # history (and more) nav tools
zsh-autosuggestions	     # auto suggestions
zsh-syntax-highlighting  # !! must be last - syntx hl
#zsh-vim-mode
)

# ZSH Autosuggest
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=1

# Zsh Syntax Highlight
typeset -A ZSH_HIGHLIGHT_STYLES

# Zsh Record Mode (used for svgterm apps)
if [ -n "$ZSH_REC_MODE" ]; then
  echo "ZSH LOADED IN REC MODE"
  noload=(zsh-autosuggestions)
  for p in ${noload[@]}; do
    plugins=(${plugins[@]/$p/} zsh-vim-mode)
  done
  echo $plugins
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
  ZSH_HIGHLIGHT_STYLES[unknown - token]=none
  alias lstree="tree -a -L 2"
fi

# ZSH Syntax Highlight
ZSH_HIGHLIGHT_STYLES[path]=cyan

# ZSH-NVM Config
#export NVM_DIR="$HOME/.nvm"
#export NVM_LAZY_LOAD=true # Get rid of a 3s startup time
#export NVM_NO_USE=true

# SSH Agent Config
##: enables ssh agent forwarding support
#zstyle :omz:plugins:ssh-agent agent-forwarding on
##: identites to load
#zstyle :omz:plugins:ssh-agent identities id_rsa id_git aur
##: helper
#zstyle :omz:plugins:ssh-agent helper ksshaskpass

# Zsh Alias Finder
ZSH_ALIAS_FINDER_AUTOMATIC=true

# Zsh Alias Tips
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES="_ ll vi vim l la g ls cat"

# Load Oh-My-Zsh
source $ZSH/oh-my-zsh.sh


## User configuration

# Report ZSH Profiling
#zprof

systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK

source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"

# (asdf) compinit
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

## Powershell10k
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
