#!/usr/bin/env bash

. utils.bash

DO_UPDATE=0



main() {
	local -A fg
	make_colors fg
	plugin="${1}"
	current="$(asdf current "${plugin}" | awk '{print $2}')"
	latest=$(asdf latest "${plugin}")
	if [ "$current" = "$latest" ]; then
		printf "%s%s | Current: %s | Latest: %s\n%s" "${fg[black]}" "$plugin" "$current" "$latest" "${fg[reset]}"
	else
		printf "%s%s | Current: %s | Latest: %s%s\n%s" "${fg[red]}" "$plugin" "$current" "${fg[bold]}" "$latest" "${fg[reset]}"
		if [ $DO_UPDATE -eq 1 ]; then
			printf "Updating: %s (%s) => (%s)\n" "$plugin" "${fg[red]}${current}${fg[reset]}" "${fg[green]}${latest}${fg[reset]}"
			asdf install "$plugin" "$latest"
			asdf local "$plugin" "$latest"
		fi
	fi
}

plugin="${1}"
shift 1

while [[ ${1} != "" ]]; do
	case "${1}" in
	-u)
		DO_UPDATE=1
		;;
	--update)
		DO_UPDATE=1
		;;
	esac
	shift 1
done

main "$plugin"
