#!/usr/bin/env bash

set -euo pipefail



main() {
  APP_PATH="${1:?err}"
  shift

  ELECTRON_PATH="/usr/bin/electron"

  if [[ "${APP_PATH}" = *bin/electron* ]]; then
    ELECTRON_PATH="${APP_PATH}"
    APP_PATH="${1:?err}"
    shift
  fi


  declare -a APP_ARGS
  APP_ARGS+=( "${@}" )


  if [ "${XDG_SESSION_TYPE}" = "wayland" ]; then
    APP_ARGS+=("--enable-accelerated-video-decode" "--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,VaapiVideoDecoder" "--ozone-platform=wayland")
  fi

  printf "Executing electron (%s) app @ %s with (%s) args.\n" "$ELECTRON_PATH" "$APP_PATH" "${APP_ARGS[*]}"
  exec "$ELECTRON_PATH" "$APP_PATH" "${APP_ARGS[@]}"
}

main "$@"
