#!/bin/sh

#
# Import GTK settings.
# usage: import-gsettings
# see: https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland#setting-values-in-gsettings
#

config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
if [ ! -f "$config" ]; then exit 1; fi

gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$config" | sed 's/.*\s*=\s*//')"
icon_theme="$(grep 'gtk-icon-theme-name' "$config" | sed 's/.*\s*=\s*//')"
cursor_theme="$(grep 'gtk-cursor-theme-name' "$config" | sed 's/.*\s*=\s*//')"
font_name="$(grep 'gtk-font-name' "$config" | sed 's/.*\s*=\s*//')"

printf "gtk-theme,$gtk_theme\nicon-theme,$icon_theme\ncursor-theme,$cursor_theme\nfont-name,$font_name\n" | column --table --separator=,

#gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
#gsettings set "$gnome_schema" icon-theme "$icon_theme"
#gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
#gsettings set "$gnome_schema" font-name "$font_name"
