#!/usr/bin/env bash

set -o pipefail

. utils.bash

# Rip Grep Replace

main() {
	local -A fg
	make_colors fg
	FIND="${1?No find arg provided.}"
	REPLACE="${2?No replace arg provided.}"
	shift
	shift

	echo "Finding and replacing all instances of < ${fg[bold]}${fg[magenta]}${FIND}${fg[reset]} > with < ${fg[bold]}${fg[cyan]}${REPLACE}${fg[reset]} >"
	echo
	sleep 1

	rg -F "$FIND" "${@}"

	sleep 3

	rg -F "$FIND" --files-with-matches "${@}" | xargs sed -i "s#$FIND#$REPLACE#g"

	printf "\n\nResults:\n\n"

	rg -F "$REPLACE" "${@}"

}

main "$@"
