#!/usr/bin/env bash

# Vars
ISO_DATE=$(date +"%Y-%m-%dT%H-%M-%S")

# Take video
srecord () {
  local file_name=${1:-"/tmp/recording_$ISO_DATE.mp4"}
  local geom _geom width height do_confirm resp
  geom="$(select-area)"
  echo "GEOM: $geom"
  read -r _ _geom <<<"$geom"
  read -r width height <<<"$(echo "${_geom}" | tr 'x' ' ')"
  echo "Target: ${width}x${height}"
  test "$width" -le 50 && do_confirm=1
  test "$height" -le 50 && do_confirm=1
  if [ -n "$do_confirm" ]; then
      read -rp "Unlikely small geom detected (${width}x${height}). Continue anyways? [y/n]: " resp
      [[ "$resp" == *y* ]] && echo "Continuing..." || exit 1
  fi
  wf-recorder -f "${file_name}" --geometry="${geom}"
  echo "Recording saved to: $file_name"
  notify-send 'Success!' "Screen recording save to: $file_name"
  mpv "$file_name" &
}

srecord "${@}"
