#!/usr/bin/env bash

set -euo pipefail
# shellcheck disable=SC2154
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

. utils.bash

get_ide_path() {
	local name="${1?}"
	local path="${2:-$name}"
	local base="${3:-opt}"
	printf "/%s/%s/bin/%s.sh" "$base" "$path" "$name"
}

get_ide() {
	local ide="${1?No ide provided!}"
	local ide_path

	case "$ide" in
	py*)
		# ide_path=$(get_ide_path "pycharm" "pycharm-eap")
		ide_path=$(get_ide_path "pycharm" "pycharm")
		;;
	web*)
		# ide_path=$(get_ide_path "webstorm" "webstorm-eap")
		ide_path=$(get_ide_path "webstorm" "webstorm")
		;;
	rider*)
		ide_path=$(get_ide_path "rider" "rider" "/usr/share")
		;;
	data*)
		ide_path=$(get_ide_path "datagrip")
		;;
	idea*)
		ide_path=$(get_ide_path "intellij-idea-ultimate-edition" "idea")
		;;
	rust*)
		ide_path=$(get_ide_path "rustrover")
		;;
	go*)
		ide_path=$(get_ide_path "goland")
		;;
	and*)
		ide_path=$(get_ide_path "studio" "android-studio")
		;;
	*)
		fail "No ide found matching: ${ide}"
		;;
	esac

	echo -n "$ide_path"
}

ensure_xsettings() {
	local unit_state
	unit_state=$(systemctl --user is-active xsettingsd.service || true)
	log_info "xsettingsd state: ${unit_state}"
	if [[ "$unit_state" = "inactive" ]]; then
		log_info "Starting xsettingsd.service!"
		systemctl --user start xsettingsd.service
	fi
}

ensure_asd() {
	local asd_marker="/tmp/jetbrains.did_asd"
	if [[ -f "$asd_marker" ]]; then
		log_info "asd already resynced, skipping"
	else
		sudo asd resync
		touch "$asd_marker"
	fi
}

main() {
	local ide_target ide_path ide_proc_log
	ide_target=${1?No IDE provided!}
	ide_path=$(get_ide "${ide_target}")
	ide_proc_log="/tmp/jetbrains_${ide_target}.log"

	ensure_xsettings
	ensure_asd
	log_info "Launching ide at: ${ide_path} (logs: ${ide_proc_log})"
	#JETBRAINS_ENABLE_EAGER_PAINT=1
	nohup vk_pro env _JAVA_AWT_WM_NONREPARENTING=1 XDG_SESSION_TYPE=wayland GDK_BACKEND=wayland QT_QPA_PLATFORM=wayland SWT_GTK3=1 AWT_TOOLKIT=WLToolkit JETBRAINS_FORCE_WAYLAND=1 JBR_WAYLAND=1 "$ide_path" >>"${ide_proc_log}" &
	#nohup env _JAVA_AWT_WM_NONREPARENTING=1 "$ide_path" >>"${ide_proc_log}" &

}

main "$@"
