import:
  - ~/.config/alacritty/monokai-soda.yml

# Window
window:
  padding:
    x: 2
    y: 2
  scrolling:
    # doubled from 10,000 default.
    history: 20000
    multiplier: 3

# Font Configuration
font:
  size: 12.0
  # size: 22
  normal:
    family: MesloLGS NF
  builtin_box_drawing: true
  draw_bold_text_with_bright_colors: true

colors:
  transparent_background_colors: true

# Cursor Config
cursor:
  style:
    shape: Beam
  vi_mode_style:
    shape: Block

# Mouse
#mouse:
#        hide_when_typing: true
#url:
#modifiers: Control

# Key bindings
key_bindings:
  - { key: L, mods: Control|Shift, action: ClearHistory }
  # - { key: Q, mods: Control|Shift, action: Quit }
  # - { key: Z, mods: Control|Shift, action: ToggleFullscreen }

  - { key: Equals, mods: Control, action: ResetFontSize }
  - { key: NumpadAdd, mods: Control, action: IncreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }

  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Return, mods: Shift, chars: "\x1b[13;2u" }
  - { key: Return, mods: Control, chars: "\x1b[13;5u" }
